/**
 * Converts a SessionResponse-like object to a Markdown report.
 */
export function sessionToMarkdown(session: {
  inputText: string;
  level: string;
  primaryIssue: string;
  correctedVersion: string;
  tutorFeedback: string;
  linguisticInsight: string;
  findingsJson: string;
  practiceJson: string;
  contrastiveJson: string | null;
  createdAt: Date | string;
}): string {
  const date = new Date(session.createdAt).toLocaleString("en-US", {
    year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  let findings: any[] = [];
  let practice: any[] = [];
  let contrastive: any = null;

  try { findings = JSON.parse(session.findingsJson); } catch {}
  try { practice = JSON.parse(session.practiceJson); } catch {}
  try { if (session.contrastiveJson) contrastive = JSON.parse(session.contrastiveJson); } catch {}

  const lines: string[] = [
    `# LinguaLens — Session Report`,
    ``,
    `**Date:** ${date}  `,
    `**Level:** ${session.level}  `,
    ``,
    `---`,
    ``,
    `## Input Text`,
    ``,
    `> ${session.inputText}`,
    ``,
    `---`,
    ``,
    `## Diagnosis`,
    ``,
    `**Primary issue:** ${session.primaryIssue}`,
    ``,
    `**Feedback:** ${session.tutorFeedback}`,
    ``,
    `**Corrected version:**`,
    ``,
    `\`\`\``,
    session.correctedVersion,
    `\`\`\``,
    ``,
    `**Linguistic insight:** ${session.linguisticInsight}`,
    ``,
  ];

  if (contrastive?.likelyTransfer) {
    lines.push(`### 🇪🇸 Spanish Transfer`, ``);
    if (contrastive.pattern) lines.push(`**Pattern:** ${contrastive.pattern}`, ``);
    if (contrastive.explanation) lines.push(contrastive.explanation, ``);
    if (contrastive.examplePair) {
      lines.push(`| Spanish-like form | Natural English |`);
      lines.push(`|---|---|`);
      lines.push(`| ${contrastive.examplePair.spanishLikeForm} | ${contrastive.examplePair.naturalEnglishForm} |`);
      lines.push(``);
    }
  }

  if (findings.length > 0) {
    lines.push(`---`, ``, `## Error Breakdown`, ``);
    lines.push(`| Span | Category | Subtype | Severity | Explanation | Fix |`);
    lines.push(`|---|---|---|---|---|---|`);
    for (const f of findings) {
      lines.push(`| \`${f.span}\` | ${f.category} | ${f.subtype} | **${f.severity}** | ${f.explanation} | ${f.suggestedFix ?? "—"} |`);
    }
    lines.push(``);
  }

  if (practice.length > 0) {
    lines.push(`---`, ``, `## Practice Exercises`, ``);
    practice.forEach((ex: any, i: number) => {
      lines.push(`### Exercise ${i + 1} (${ex.type})`, ``);
      lines.push(`**Prompt:** ${ex.prompt}`, ``);
      if (ex.answer) lines.push(`**Answer:** ${ex.answer}`, ``);
      lines.push(`*Teaching point: ${ex.teachingPoint}*`, ``);
    });
  }

  lines.push(`---`, ``, `*Generated by LinguaLens — English through Applied Linguistics*`);

  return lines.join("\n");
}
